# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tweet_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_text', models.CharField(max_length=200)),
                ('tweet_user', models.CharField(max_length=200)),
                ('tweet_date', models.DateTimeField(verbose_name='date published')),
                ('tweet_polarity', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Sentiment')),
                ('tweet_subjectivity', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Sentiment')),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sentiment.SearchTerm')),
            ],
        ),
    ]
